package com.masiis.shop.dao;

import com.masiis.shop.dao.ComArea;
import com.masiis.shop.dao.ComAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ComAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(ComAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(ComAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from com_area",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into com_area (id, create_time, ",
        "create_man, code, ",
        "name, pid, level, ",
        "name_en, shortname_en, ",
        "sort, remark)",
        "values (#{id,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createMan,jdbcType=BIGINT}, #{code,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{pid,jdbcType=INTEGER}, #{level,jdbcType=INTEGER}, ",
        "#{nameEn,jdbcType=VARCHAR}, #{shortnameEn,jdbcType=VARCHAR}, ",
        "#{sort,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(ComArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(ComArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<ComArea> selectByExample(ComAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, create_man, code, name, pid, level, name_en, shortname_en, ",
        "sort, remark",
        "from com_area",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ComArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") ComArea record, @Param("example") ComAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") ComArea record, @Param("example") ComAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(ComArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_area
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update com_area",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_man = #{createMan,jdbcType=BIGINT},",
          "code = #{code,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=INTEGER},",
          "level = #{level,jdbcType=INTEGER},",
          "name_en = #{nameEn,jdbcType=VARCHAR},",
          "shortname_en = #{shortnameEn,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ComArea record);
}