package com.masiis.shop.dao;

import java.util.Date;

public class ComArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.level
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.name_en
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.shortname_en
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String shortnameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.sort
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_area.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.id
     *
     * @return the value of com_area.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.id
     *
     * @param id the value for com_area.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.create_time
     *
     * @return the value of com_area.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.create_time
     *
     * @param createTime the value for com_area.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.create_man
     *
     * @return the value of com_area.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.create_man
     *
     * @param createMan the value for com_area.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateMan(Long createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.code
     *
     * @return the value of com_area.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.code
     *
     * @param code the value for com_area.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.name
     *
     * @return the value of com_area.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.name
     *
     * @param name the value for com_area.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.pid
     *
     * @return the value of com_area.pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.pid
     *
     * @param pid the value for com_area.pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.level
     *
     * @return the value of com_area.level
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.level
     *
     * @param level the value for com_area.level
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.name_en
     *
     * @return the value of com_area.name_en
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.name_en
     *
     * @param nameEn the value for com_area.name_en
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.shortname_en
     *
     * @return the value of com_area.shortname_en
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getShortnameEn() {
        return shortnameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.shortname_en
     *
     * @param shortnameEn the value for com_area.shortname_en
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setShortnameEn(String shortnameEn) {
        this.shortnameEn = shortnameEn == null ? null : shortnameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.sort
     *
     * @return the value of com_area.sort
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.sort
     *
     * @param sort the value for com_area.sort
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_area.remark
     *
     * @return the value of com_area.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_area.remark
     *
     * @param remark the value for com_area.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}