package com.masiis.shop.dao;

import com.masiis.shop.dao.ComBrand;
import com.masiis.shop.dao.ComBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ComBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(ComBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(ComBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from com_brand",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into com_brand (id, create_time, ",
        "cname, ename, logo_url, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{cname,jdbcType=VARCHAR}, #{ename,jdbcType=VARCHAR}, #{logoUrl,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(ComBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(ComBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<ComBrand> selectByExample(ComBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, cname, ename, logo_url, remark",
        "from com_brand",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ComBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") ComBrand record, @Param("example") ComBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") ComBrand record, @Param("example") ComBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(ComBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_brand
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update com_brand",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "cname = #{cname,jdbcType=VARCHAR},",
          "ename = #{ename,jdbcType=VARCHAR},",
          "logo_url = #{logoUrl,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ComBrand record);
}