package com.masiis.shop.dao;

public class ComDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_dictionary.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_dictionary.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_dictionary.key
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_dictionary.value
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_dictionary.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_dictionary.id
     *
     * @return the value of com_dictionary.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_dictionary.id
     *
     * @param id the value for com_dictionary.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_dictionary.code
     *
     * @return the value of com_dictionary.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_dictionary.code
     *
     * @param code the value for com_dictionary.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_dictionary.key
     *
     * @return the value of com_dictionary.key
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_dictionary.key
     *
     * @param key the value for com_dictionary.key
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setKey(Integer key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_dictionary.value
     *
     * @return the value of com_dictionary.value
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_dictionary.value
     *
     * @param value the value for com_dictionary.value
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_dictionary.remark
     *
     * @return the value of com_dictionary.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_dictionary.remark
     *
     * @param remark the value for com_dictionary.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}