package com.masiis.shop.dao;

import com.masiis.shop.dao.ComDictionary;
import com.masiis.shop.dao.ComDictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ComDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(ComDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(ComDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from com_dictionary",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into com_dictionary (id, code, ",
        "key, value, remark)",
        "values (#{id,jdbcType=INTEGER}, #{code,jdbcType=VARCHAR}, ",
        "#{key,jdbcType=INTEGER}, #{value,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(ComDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(ComDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<ComDictionary> selectByExample(ComDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, code, key, value, remark",
        "from com_dictionary",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ComDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") ComDictionary record, @Param("example") ComDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") ComDictionary record, @Param("example") ComDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(ComDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_dictionary
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update com_dictionary",
        "set code = #{code,jdbcType=VARCHAR},",
          "key = #{key,jdbcType=INTEGER},",
          "value = #{value,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ComDictionary record);
}