package com.masiis.shop.dao;

import java.util.Date;

public class ComSkuImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.spu_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer spuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.img_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.is_default
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.sort
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku_image.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.id
     *
     * @return the value of com_sku_image.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.id
     *
     * @param id the value for com_sku_image.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.create_time
     *
     * @return the value of com_sku_image.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.create_time
     *
     * @param createTime the value for com_sku_image.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.create_man
     *
     * @return the value of com_sku_image.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.create_man
     *
     * @param createMan the value for com_sku_image.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateMan(Long createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.spu_id
     *
     * @return the value of com_sku_image.spu_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.spu_id
     *
     * @param spuId the value for com_sku_image.spu_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.sku_id
     *
     * @return the value of com_sku_image.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.sku_id
     *
     * @param skuId the value for com_sku_image.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.img_name
     *
     * @return the value of com_sku_image.img_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.img_name
     *
     * @param imgName the value for com_sku_image.img_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.img_url
     *
     * @return the value of com_sku_image.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.img_url
     *
     * @param imgUrl the value for com_sku_image.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.modify_time
     *
     * @return the value of com_sku_image.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.modify_time
     *
     * @param modifyTime the value for com_sku_image.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.modify_man
     *
     * @return the value of com_sku_image.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.modify_man
     *
     * @param modifyMan the value for com_sku_image.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setModifyMan(Long modifyMan) {
        this.modifyMan = modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.is_default
     *
     * @return the value of com_sku_image.is_default
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.is_default
     *
     * @param isDefault the value for com_sku_image.is_default
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.sort
     *
     * @return the value of com_sku_image.sort
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.sort
     *
     * @param sort the value for com_sku_image.sort
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku_image.remark
     *
     * @return the value of com_sku_image.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku_image.remark
     *
     * @param remark the value for com_sku_image.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}