package com.masiis.shop.dao;

import java.util.Date;

public class ComSpuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.category_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.category_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.is_sale
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.is_delete
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.id
     *
     * @return the value of com_spu.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.id
     *
     * @param id the value for com_spu.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.name
     *
     * @return the value of com_spu.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.name
     *
     * @param name the value for com_spu.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.create_time
     *
     * @return the value of com_spu.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.create_time
     *
     * @param createTime the value for com_spu.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.create_man
     *
     * @return the value of com_spu.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.create_man
     *
     * @param createMan the value for com_spu.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateMan(Long createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.category_id
     *
     * @return the value of com_spu.category_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.category_id
     *
     * @param categoryId the value for com_spu.category_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.category_name
     *
     * @return the value of com_spu.category_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.category_name
     *
     * @param categoryName the value for com_spu.category_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.status
     *
     * @return the value of com_spu.status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.status
     *
     * @param status the value for com_spu.status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.is_sale
     *
     * @return the value of com_spu.is_sale
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsSale() {
        return isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.is_sale
     *
     * @param isSale the value for com_spu.is_sale
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsSale(Integer isSale) {
        this.isSale = isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.is_delete
     *
     * @return the value of com_spu.is_delete
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.is_delete
     *
     * @param isDelete the value for com_spu.is_delete
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}