package com.masiis.shop.dao;

import java.util.Date;

public class ComSpu extends ComSpuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.brand_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.up_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.down_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date downTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.slogan
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String slogan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.is_trial
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isTrial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.content
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.weight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.pack_length
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long packLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.pack_width
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long packWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.pack_height
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long packHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.brand_id
     *
     * @return the value of com_spu.brand_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.brand_id
     *
     * @param brandId the value for com_spu.brand_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.up_time
     *
     * @return the value of com_spu.up_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.up_time
     *
     * @param upTime the value for com_spu.up_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.down_time
     *
     * @return the value of com_spu.down_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getDownTime() {
        return downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.down_time
     *
     * @param downTime the value for com_spu.down_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setDownTime(Date downTime) {
        this.downTime = downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.modify_time
     *
     * @return the value of com_spu.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.modify_time
     *
     * @param modifyTime the value for com_spu.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.modify_man
     *
     * @return the value of com_spu.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.modify_man
     *
     * @param modifyMan the value for com_spu.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setModifyMan(Long modifyMan) {
        this.modifyMan = modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.slogan
     *
     * @return the value of com_spu.slogan
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.slogan
     *
     * @param slogan the value for com_spu.slogan
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan == null ? null : slogan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.is_trial
     *
     * @return the value of com_spu.is_trial
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsTrial() {
        return isTrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.is_trial
     *
     * @param isTrial the value for com_spu.is_trial
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsTrial(Integer isTrial) {
        this.isTrial = isTrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.content
     *
     * @return the value of com_spu.content
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.content
     *
     * @param content the value for com_spu.content
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.weight
     *
     * @return the value of com_spu.weight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.weight
     *
     * @param weight the value for com_spu.weight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.pack_length
     *
     * @return the value of com_spu.pack_length
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getPackLength() {
        return packLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.pack_length
     *
     * @param packLength the value for com_spu.pack_length
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPackLength(Long packLength) {
        this.packLength = packLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.pack_width
     *
     * @return the value of com_spu.pack_width
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getPackWidth() {
        return packWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.pack_width
     *
     * @param packWidth the value for com_spu.pack_width
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPackWidth(Long packWidth) {
        this.packWidth = packWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.pack_height
     *
     * @return the value of com_spu.pack_height
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getPackHeight() {
        return packHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.pack_height
     *
     * @param packHeight the value for com_spu.pack_height
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPackHeight(Long packHeight) {
        this.packHeight = packHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.remark
     *
     * @return the value of com_spu.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.remark
     *
     * @param remark the value for com_spu.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}