package com.masiis.shop.dao;

import java.util.Date;

public class ComUserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.zip
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.is_default
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user_address.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.id
     *
     * @return the value of com_user_address.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.id
     *
     * @param id the value for com_user_address.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.create_time
     *
     * @return the value of com_user_address.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.create_time
     *
     * @param createTime the value for com_user_address.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.user_id
     *
     * @return the value of com_user_address.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.user_id
     *
     * @param userId the value for com_user_address.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.name
     *
     * @return the value of com_user_address.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.name
     *
     * @param name the value for com_user_address.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.zip
     *
     * @return the value of com_user_address.zip
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.zip
     *
     * @param zip the value for com_user_address.zip
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.province_id
     *
     * @return the value of com_user_address.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.province_id
     *
     * @param provinceId the value for com_user_address.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.province_name
     *
     * @return the value of com_user_address.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.province_name
     *
     * @param provinceName the value for com_user_address.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.city_id
     *
     * @return the value of com_user_address.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.city_id
     *
     * @param cityId the value for com_user_address.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.city_name
     *
     * @return the value of com_user_address.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.city_name
     *
     * @param cityName the value for com_user_address.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.region_id
     *
     * @return the value of com_user_address.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.region_id
     *
     * @param regionId the value for com_user_address.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.region_name
     *
     * @return the value of com_user_address.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.region_name
     *
     * @param regionName the value for com_user_address.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.address
     *
     * @return the value of com_user_address.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.address
     *
     * @param address the value for com_user_address.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.mobile
     *
     * @return the value of com_user_address.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.mobile
     *
     * @param mobile the value for com_user_address.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.is_default
     *
     * @return the value of com_user_address.is_default
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.is_default
     *
     * @param isDefault the value for com_user_address.is_default
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user_address.remark
     *
     * @return the value of com_user_address.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user_address.remark
     *
     * @param remark the value for com_user_address.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}