package com.masiis.shop.dao;

import java.util.Date;

public class ComUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.openid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.wx_nk_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String wxNkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.wx_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String wxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.wx_head_img
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String wxHeadImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.access_token
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.refresh_token
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.atoken_expire
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date atokenExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.rtoken_expire
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date rtokenExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.real_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.id_card
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.id_card_front_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String idCardFrontUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.id_card_back_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String idCardBackUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.is_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_user.sex
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.id
     *
     * @return the value of com_user.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.id
     *
     * @param id the value for com_user.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.create_time
     *
     * @return the value of com_user.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.create_time
     *
     * @param createTime the value for com_user.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.openid
     *
     * @return the value of com_user.openid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.openid
     *
     * @param openid the value for com_user.openid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.wx_nk_name
     *
     * @return the value of com_user.wx_nk_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getWxNkName() {
        return wxNkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.wx_nk_name
     *
     * @param wxNkName the value for com_user.wx_nk_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setWxNkName(String wxNkName) {
        this.wxNkName = wxNkName == null ? null : wxNkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.wx_id
     *
     * @return the value of com_user.wx_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.wx_id
     *
     * @param wxId the value for com_user.wx_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.wx_head_img
     *
     * @return the value of com_user.wx_head_img
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getWxHeadImg() {
        return wxHeadImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.wx_head_img
     *
     * @param wxHeadImg the value for com_user.wx_head_img
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setWxHeadImg(String wxHeadImg) {
        this.wxHeadImg = wxHeadImg == null ? null : wxHeadImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.access_token
     *
     * @return the value of com_user.access_token
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.access_token
     *
     * @param accessToken the value for com_user.access_token
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.refresh_token
     *
     * @return the value of com_user.refresh_token
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.refresh_token
     *
     * @param refreshToken the value for com_user.refresh_token
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.atoken_expire
     *
     * @return the value of com_user.atoken_expire
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getAtokenExpire() {
        return atokenExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.atoken_expire
     *
     * @param atokenExpire the value for com_user.atoken_expire
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAtokenExpire(Date atokenExpire) {
        this.atokenExpire = atokenExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.rtoken_expire
     *
     * @return the value of com_user.rtoken_expire
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getRtokenExpire() {
        return rtokenExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.rtoken_expire
     *
     * @param rtokenExpire the value for com_user.rtoken_expire
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRtokenExpire(Date rtokenExpire) {
        this.rtokenExpire = rtokenExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.real_name
     *
     * @return the value of com_user.real_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.real_name
     *
     * @param realName the value for com_user.real_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.mobile
     *
     * @return the value of com_user.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.mobile
     *
     * @param mobile the value for com_user.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.id_card
     *
     * @return the value of com_user.id_card
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.id_card
     *
     * @param idCard the value for com_user.id_card
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.id_card_front_url
     *
     * @return the value of com_user.id_card_front_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getIdCardFrontUrl() {
        return idCardFrontUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.id_card_front_url
     *
     * @param idCardFrontUrl the value for com_user.id_card_front_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIdCardFrontUrl(String idCardFrontUrl) {
        this.idCardFrontUrl = idCardFrontUrl == null ? null : idCardFrontUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.id_card_back_url
     *
     * @return the value of com_user.id_card_back_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getIdCardBackUrl() {
        return idCardBackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.id_card_back_url
     *
     * @param idCardBackUrl the value for com_user.id_card_back_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIdCardBackUrl(String idCardBackUrl) {
        this.idCardBackUrl = idCardBackUrl == null ? null : idCardBackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.province_id
     *
     * @return the value of com_user.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.province_id
     *
     * @param provinceId the value for com_user.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.province_name
     *
     * @return the value of com_user.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.province_name
     *
     * @param provinceName the value for com_user.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.city_id
     *
     * @return the value of com_user.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.city_id
     *
     * @param cityId the value for com_user.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.city_name
     *
     * @return the value of com_user.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.city_name
     *
     * @param cityName the value for com_user.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.region_id
     *
     * @return the value of com_user.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.region_id
     *
     * @param regionId the value for com_user.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.region_name
     *
     * @return the value of com_user.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.region_name
     *
     * @param regionName the value for com_user.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.address
     *
     * @return the value of com_user.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.address
     *
     * @param address the value for com_user.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.is_agent
     *
     * @return the value of com_user.is_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsAgent() {
        return isAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.is_agent
     *
     * @param isAgent the value for com_user.is_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsAgent(Integer isAgent) {
        this.isAgent = isAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_user.sex
     *
     * @return the value of com_user.sex
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_user.sex
     *
     * @param sex the value for com_user.sex
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }
}