package com.masiis.shop.dao;

import com.masiis.shop.dao.PbAnnouncement;
import com.masiis.shop.dao.PbAnnouncementExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PbAnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PbAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PbAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pb_announcement",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pb_announcement (id, create_time, ",
        "name, hyperlink_url, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{name,jdbcType=VARCHAR}, #{hyperlinkUrl,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(PbAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PbAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PbAnnouncement> selectByExample(PbAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, name, hyperlink_url, remark",
        "from pb_announcement",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PbAnnouncement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PbAnnouncement record, @Param("example") PbAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PbAnnouncement record, @Param("example") PbAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PbAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_announcement
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pb_announcement",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "name = #{name,jdbcType=VARCHAR},",
          "hyperlink_url = #{hyperlinkUrl,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PbAnnouncement record);
}