package com.masiis.shop.dao;

import com.masiis.shop.dao.PbBanner;
import com.masiis.shop.dao.PbBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PbBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pb_banner",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pb_banner (id, create_time, ",
        "name, img_url, hyperlink_url, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{name,jdbcType=VARCHAR}, #{imgUrl,jdbcType=VARCHAR}, #{hyperlinkUrl,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(PbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PbBanner> selectByExample(PbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, name, img_url, hyperlink_url, remark",
        "from pb_banner",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PbBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PbBanner record, @Param("example") PbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PbBanner record, @Param("example") PbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_banner
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pb_banner",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "name = #{name,jdbcType=VARCHAR},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "hyperlink_url = #{hyperlinkUrl,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PbBanner record);
}