package com.masiis.shop.dao;

import java.util.Date;

public class PbBanner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_banner.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_banner.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_banner.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_banner.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_banner.hyperlink_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String hyperlinkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_banner.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_banner.id
     *
     * @return the value of pb_banner.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_banner.id
     *
     * @param id the value for pb_banner.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_banner.create_time
     *
     * @return the value of pb_banner.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_banner.create_time
     *
     * @param createTime the value for pb_banner.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_banner.name
     *
     * @return the value of pb_banner.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_banner.name
     *
     * @param name the value for pb_banner.name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_banner.img_url
     *
     * @return the value of pb_banner.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_banner.img_url
     *
     * @param imgUrl the value for pb_banner.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_banner.hyperlink_url
     *
     * @return the value of pb_banner.hyperlink_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getHyperlinkUrl() {
        return hyperlinkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_banner.hyperlink_url
     *
     * @param hyperlinkUrl the value for pb_banner.hyperlink_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setHyperlinkUrl(String hyperlinkUrl) {
        this.hyperlinkUrl = hyperlinkUrl == null ? null : hyperlinkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_banner.remark
     *
     * @return the value of pb_banner.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_banner.remark
     *
     * @param remark the value for pb_banner.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}