package com.masiis.shop.dao;

import com.masiis.shop.dao.PbOperationLog;
import com.masiis.shop.dao.PbOperationLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface PbOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PbOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PbOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pb_operation_log (id)",
        "values (#{id,jdbcType=BIGINT})"
    })
    int insert(PbOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PbOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PbOperationLog> selectByExample(PbOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PbOperationLog record, @Param("example") PbOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PbOperationLog record, @Param("example") PbOperationLogExample example);
}