package com.masiis.shop.dao;

import com.masiis.shop.dao.PbUserMenu;
import com.masiis.shop.dao.PbUserMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PbUserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PbUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PbUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pb_user_menu",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pb_user_menu (id, pb_user_id, ",
        "pb_menu_id, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{pbUserId,jdbcType=BIGINT}, ",
        "#{pbMenuId,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PbUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PbUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PbUserMenu> selectByExample(PbUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, pb_user_id, pb_menu_id, create_time, update_time",
        "from pb_user_menu",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PbUserMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PbUserMenu record, @Param("example") PbUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PbUserMenu record, @Param("example") PbUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PbUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user_menu
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pb_user_menu",
        "set pb_user_id = #{pbUserId,jdbcType=BIGINT},",
          "pb_menu_id = #{pbMenuId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PbUserMenu record);
}