package com.masiis.shop.dao;

import com.masiis.shop.dao.PbUser;
import com.masiis.shop.dao.PbUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pb_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pb_user (id, user_name, ",
        "true_name, password, ",
        "email, sex, age, ",
        "phone)",
        "values (#{id,jdbcType=BIGINT}, #{userName,jdbcType=VARCHAR}, ",
        "#{trueName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{sex,jdbcType=CHAR}, #{age,jdbcType=INTEGER}, ",
        "#{phone,jdbcType=VARCHAR})"
    })
    int insert(PbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PbUser> selectByExample(PbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, user_name, true_name, password, email, sex, age, phone",
        "from pb_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PbUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PbUser record, @Param("example") PbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PbUser record, @Param("example") PbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pb_user
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pb_user",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "true_name = #{trueName,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=CHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "phone = #{phone,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PbUser record);
}