package com.masiis.shop.dao;

public class PbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.user_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.true_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.password
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.email
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.sex
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.age
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pb_user.phone
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.id
     *
     * @return the value of pb_user.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.id
     *
     * @param id the value for pb_user.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.user_name
     *
     * @return the value of pb_user.user_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.user_name
     *
     * @param userName the value for pb_user.user_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.true_name
     *
     * @return the value of pb_user.true_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.true_name
     *
     * @param trueName the value for pb_user.true_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.password
     *
     * @return the value of pb_user.password
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.password
     *
     * @param password the value for pb_user.password
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.email
     *
     * @return the value of pb_user.email
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.email
     *
     * @param email the value for pb_user.email
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.sex
     *
     * @return the value of pb_user.sex
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.sex
     *
     * @param sex the value for pb_user.sex
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.age
     *
     * @return the value of pb_user.age
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.age
     *
     * @param age the value for pb_user.age
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pb_user.phone
     *
     * @return the value of pb_user.phone
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pb_user.phone
     *
     * @param phone the value for pb_user.phone
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}