package com.masiis.shop.dao;

import com.masiis.shop.dao.PfBorderOperationLog;
import com.masiis.shop.dao.PfBorderOperationLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PfBorderOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfBorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfBorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pf_border_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_border_operation_log (id, create_time, ",
        "create_man, pf_border_id, ",
        "pf_border_status, remark)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createMan,jdbcType=BIGINT}, #{pfBorderId,jdbcType=BIGINT}, ",
        "#{pfBorderStatus,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PfBorderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfBorderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfBorderOperationLog> selectByExample(PfBorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, create_man, pf_border_id, pf_border_status, remark",
        "from pf_border_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PfBorderOperationLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfBorderOperationLog record, @Param("example") PfBorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfBorderOperationLog record, @Param("example") PfBorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PfBorderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pf_border_operation_log",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_man = #{createMan,jdbcType=BIGINT},",
          "pf_border_id = #{pfBorderId,jdbcType=BIGINT},",
          "pf_border_status = #{pfBorderStatus,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PfBorderOperationLog record);
}