package com.masiis.shop.dao;

import com.masiis.shop.dao.PfBorderPayment;
import com.masiis.shop.dao.PfBorderPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PfBorderPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfBorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfBorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pf_border_payment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_border_payment (id, create_time, ",
        "pf_border_id, amount, ",
        "pay_type_id, pay_type_name, ",
        "is_enabled, remark)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{pfBorderId,jdbcType=BIGINT}, #{amount,jdbcType=DECIMAL}, ",
        "#{payTypeId,jdbcType=INTEGER}, #{payTypeName,jdbcType=VARCHAR}, ",
        "#{isEnabled,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PfBorderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfBorderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfBorderPayment> selectByExample(PfBorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, pf_border_id, amount, pay_type_id, pay_type_name, is_enabled, ",
        "remark",
        "from pf_border_payment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PfBorderPayment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfBorderPayment record, @Param("example") PfBorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfBorderPayment record, @Param("example") PfBorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PfBorderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pf_border_payment",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "pf_border_id = #{pfBorderId,jdbcType=BIGINT},",
          "amount = #{amount,jdbcType=DECIMAL},",
          "pay_type_id = #{payTypeId,jdbcType=INTEGER},",
          "pay_type_name = #{payTypeName,jdbcType=VARCHAR},",
          "is_enabled = #{isEnabled,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PfBorderPayment record);
}