package com.masiis.shop.dao;

import com.masiis.shop.dao.PfBorderFreight;
import com.masiis.shop.dao.PfBorderFreightExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface PfBorderFreightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfBorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfBorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_border_freight (id, create_time, ",
        "pf_corder_id, ship_man_id, ",
        "ship_man_name, freight)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{pfCorderId,jdbcType=BIGINT}, #{shipManId,jdbcType=INTEGER}, ",
        "#{shipManName,jdbcType=VARCHAR}, #{freight,jdbcType=VARCHAR})"
    })
    int insert(PfBorderFreight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfBorderFreight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfBorderFreight> selectByExample(PfBorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfBorderFreight record, @Param("example") PfBorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_border_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfBorderFreight record, @Param("example") PfBorderFreightExample example);
}