package com.masiis.shop.dao;

import java.util.Date;

public class PfBorderConsignee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.pf_border_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long pfBorderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_border_consignee.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.id
     *
     * @return the value of pf_border_consignee.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.id
     *
     * @param id the value for pf_border_consignee.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.create_time
     *
     * @return the value of pf_border_consignee.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.create_time
     *
     * @param createTime the value for pf_border_consignee.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.pf_border_id
     *
     * @return the value of pf_border_consignee.pf_border_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getPfBorderId() {
        return pfBorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.pf_border_id
     *
     * @param pfBorderId the value for pf_border_consignee.pf_border_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPfBorderId(Long pfBorderId) {
        this.pfBorderId = pfBorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.user_id
     *
     * @return the value of pf_border_consignee.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.user_id
     *
     * @param userId the value for pf_border_consignee.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.consignee
     *
     * @return the value of pf_border_consignee.consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.consignee
     *
     * @param consignee the value for pf_border_consignee.consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.mobile
     *
     * @return the value of pf_border_consignee.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.mobile
     *
     * @param mobile the value for pf_border_consignee.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.province_id
     *
     * @return the value of pf_border_consignee.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.province_id
     *
     * @param provinceId the value for pf_border_consignee.province_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.province_name
     *
     * @return the value of pf_border_consignee.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.province_name
     *
     * @param provinceName the value for pf_border_consignee.province_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.city_id
     *
     * @return the value of pf_border_consignee.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.city_id
     *
     * @param cityId the value for pf_border_consignee.city_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.city_name
     *
     * @return the value of pf_border_consignee.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.city_name
     *
     * @param cityName the value for pf_border_consignee.city_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.region_id
     *
     * @return the value of pf_border_consignee.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.region_id
     *
     * @param regionId the value for pf_border_consignee.region_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.region_name
     *
     * @return the value of pf_border_consignee.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.region_name
     *
     * @param regionName the value for pf_border_consignee.region_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.address
     *
     * @return the value of pf_border_consignee.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.address
     *
     * @param address the value for pf_border_consignee.address
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_border_consignee.remark
     *
     * @return the value of pf_border_consignee.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_border_consignee.remark
     *
     * @param remark the value for pf_border_consignee.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}