package com.masiis.shop.dao;

import com.masiis.shop.dao.PfCorderConsignee;
import com.masiis.shop.dao.PfCorderConsigneeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PfCorderConsigneeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfCorderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfCorderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pf_corder_consignee",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_corder_consignee (id, create_time, ",
        "pf_corder_id, user_id, ",
        "consignee, mobile, ",
        "province_id, province_name, ",
        "city_id, city_name, ",
        "region_id, region_name, ",
        "address, remark)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{pfCorderId,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{consignee,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{provinceId,jdbcType=INTEGER}, #{provinceName,jdbcType=VARCHAR}, ",
        "#{cityId,jdbcType=INTEGER}, #{cityName,jdbcType=VARCHAR}, ",
        "#{regionId,jdbcType=INTEGER}, #{regionName,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PfCorderConsignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfCorderConsignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfCorderConsignee> selectByExample(PfCorderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, pf_corder_id, user_id, consignee, mobile, province_id, province_name, ",
        "city_id, city_name, region_id, region_name, address, remark",
        "from pf_corder_consignee",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PfCorderConsignee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfCorderConsignee record, @Param("example") PfCorderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfCorderConsignee record, @Param("example") PfCorderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PfCorderConsignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pf_corder_consignee",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "pf_corder_id = #{pfCorderId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "consignee = #{consignee,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "province_id = #{provinceId,jdbcType=INTEGER},",
          "province_name = #{provinceName,jdbcType=VARCHAR},",
          "city_id = #{cityId,jdbcType=INTEGER},",
          "city_name = #{cityName,jdbcType=VARCHAR},",
          "region_id = #{regionId,jdbcType=INTEGER},",
          "region_name = #{regionName,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PfCorderConsignee record);
}