package com.masiis.shop.dao;

import java.math.BigDecimal;
import java.util.Date;

public class PfCorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.order_code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.order_type
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.user_pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long userPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.user_massage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String userMassage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.supplier_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.receivable_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private BigDecimal receivableAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.order_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.product_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private BigDecimal productAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.ship_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private BigDecimal shipAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.pay_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.pay_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.ship_man_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer shipManId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.ship_man_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String shipManName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.delivery_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.ship_remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String shipRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.replace_order_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long replaceOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.order_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.ship_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer shipStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.pay_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.is_ship
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isShip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.is_replace
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isReplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.is_receipt
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.receipt_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date receiptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_corder.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.id
     *
     * @return the value of pf_corder.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.id
     *
     * @param id the value for pf_corder.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.create_time
     *
     * @return the value of pf_corder.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.create_time
     *
     * @param createTime the value for pf_corder.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.create_man
     *
     * @return the value of pf_corder.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.create_man
     *
     * @param createMan the value for pf_corder.create_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateMan(Long createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.order_code
     *
     * @return the value of pf_corder.order_code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.order_code
     *
     * @param orderCode the value for pf_corder.order_code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.order_type
     *
     * @return the value of pf_corder.order_type
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.order_type
     *
     * @param orderType the value for pf_corder.order_type
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.user_id
     *
     * @return the value of pf_corder.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.user_id
     *
     * @param userId the value for pf_corder.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.user_pid
     *
     * @return the value of pf_corder.user_pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getUserPid() {
        return userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.user_pid
     *
     * @param userPid the value for pf_corder.user_pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUserPid(Long userPid) {
        this.userPid = userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.user_massage
     *
     * @return the value of pf_corder.user_massage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getUserMassage() {
        return userMassage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.user_massage
     *
     * @param userMassage the value for pf_corder.user_massage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUserMassage(String userMassage) {
        this.userMassage = userMassage == null ? null : userMassage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.supplier_id
     *
     * @return the value of pf_corder.supplier_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.supplier_id
     *
     * @param supplierId the value for pf_corder.supplier_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.modify_time
     *
     * @return the value of pf_corder.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.modify_time
     *
     * @param modifyTime the value for pf_corder.modify_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.modify_man
     *
     * @return the value of pf_corder.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.modify_man
     *
     * @param modifyMan the value for pf_corder.modify_man
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setModifyMan(Long modifyMan) {
        this.modifyMan = modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.receivable_amount
     *
     * @return the value of pf_corder.receivable_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public BigDecimal getReceivableAmount() {
        return receivableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.receivable_amount
     *
     * @param receivableAmount the value for pf_corder.receivable_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setReceivableAmount(BigDecimal receivableAmount) {
        this.receivableAmount = receivableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.order_amount
     *
     * @return the value of pf_corder.order_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.order_amount
     *
     * @param orderAmount the value for pf_corder.order_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.product_amount
     *
     * @return the value of pf_corder.product_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public BigDecimal getProductAmount() {
        return productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.product_amount
     *
     * @param productAmount the value for pf_corder.product_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setProductAmount(BigDecimal productAmount) {
        this.productAmount = productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.ship_amount
     *
     * @return the value of pf_corder.ship_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public BigDecimal getShipAmount() {
        return shipAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.ship_amount
     *
     * @param shipAmount the value for pf_corder.ship_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setShipAmount(BigDecimal shipAmount) {
        this.shipAmount = shipAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.pay_amount
     *
     * @return the value of pf_corder.pay_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.pay_amount
     *
     * @param payAmount the value for pf_corder.pay_amount
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.pay_time
     *
     * @return the value of pf_corder.pay_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.pay_time
     *
     * @param payTime the value for pf_corder.pay_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.ship_man_id
     *
     * @return the value of pf_corder.ship_man_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getShipManId() {
        return shipManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.ship_man_id
     *
     * @param shipManId the value for pf_corder.ship_man_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setShipManId(Integer shipManId) {
        this.shipManId = shipManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.ship_man_name
     *
     * @return the value of pf_corder.ship_man_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getShipManName() {
        return shipManName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.ship_man_name
     *
     * @param shipManName the value for pf_corder.ship_man_name
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setShipManName(String shipManName) {
        this.shipManName = shipManName == null ? null : shipManName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.delivery_time
     *
     * @return the value of pf_corder.delivery_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.delivery_time
     *
     * @param deliveryTime the value for pf_corder.delivery_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.ship_remark
     *
     * @return the value of pf_corder.ship_remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getShipRemark() {
        return shipRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.ship_remark
     *
     * @param shipRemark the value for pf_corder.ship_remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setShipRemark(String shipRemark) {
        this.shipRemark = shipRemark == null ? null : shipRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.replace_order_id
     *
     * @return the value of pf_corder.replace_order_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getReplaceOrderId() {
        return replaceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.replace_order_id
     *
     * @param replaceOrderId the value for pf_corder.replace_order_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setReplaceOrderId(Long replaceOrderId) {
        this.replaceOrderId = replaceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.order_status
     *
     * @return the value of pf_corder.order_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.order_status
     *
     * @param orderStatus the value for pf_corder.order_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.ship_status
     *
     * @return the value of pf_corder.ship_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getShipStatus() {
        return shipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.ship_status
     *
     * @param shipStatus the value for pf_corder.ship_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setShipStatus(Integer shipStatus) {
        this.shipStatus = shipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.pay_status
     *
     * @return the value of pf_corder.pay_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.pay_status
     *
     * @param payStatus the value for pf_corder.pay_status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.is_ship
     *
     * @return the value of pf_corder.is_ship
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsShip() {
        return isShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.is_ship
     *
     * @param isShip the value for pf_corder.is_ship
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsShip(Integer isShip) {
        this.isShip = isShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.is_replace
     *
     * @return the value of pf_corder.is_replace
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsReplace() {
        return isReplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.is_replace
     *
     * @param isReplace the value for pf_corder.is_replace
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsReplace(Integer isReplace) {
        this.isReplace = isReplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.is_receipt
     *
     * @return the value of pf_corder.is_receipt
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.is_receipt
     *
     * @param isReceipt the value for pf_corder.is_receipt
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsReceipt(Integer isReceipt) {
        this.isReceipt = isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.receipt_time
     *
     * @return the value of pf_corder.receipt_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getReceiptTime() {
        return receiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.receipt_time
     *
     * @param receiptTime the value for pf_corder.receipt_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setReceiptTime(Date receiptTime) {
        this.receiptTime = receiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_corder.remark
     *
     * @return the value of pf_corder.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_corder.remark
     *
     * @param remark the value for pf_corder.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}