package com.masiis.shop.dao;

import com.masiis.shop.dao.PfCorderFreight;
import com.masiis.shop.dao.PfCorderFreightExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface PfCorderFreightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfCorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfCorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_corder_freight (id, create_time, ",
        "pf_corder_id, ship_man_id, ",
        "ship_man_name, freight)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{pfCorderId,jdbcType=BIGINT}, #{shipManId,jdbcType=INTEGER}, ",
        "#{shipManName,jdbcType=VARCHAR}, #{freight,jdbcType=VARCHAR})"
    })
    int insert(PfCorderFreight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfCorderFreight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfCorderFreight> selectByExample(PfCorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfCorderFreight record, @Param("example") PfCorderFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_freight
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfCorderFreight record, @Param("example") PfCorderFreightExample example);
}