package com.masiis.shop.dao;

import com.masiis.shop.dao.PfCorderPayment;
import com.masiis.shop.dao.PfCorderPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PfCorderPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfCorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfCorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pf_corder_payment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_corder_payment (id, create_time, ",
        "pf_corder_id, amount, ",
        "pay_type_id, pay_type_name, ",
        "is_enabled, remark)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{pfCorderId,jdbcType=BIGINT}, #{amount,jdbcType=DECIMAL}, ",
        "#{payTypeId,jdbcType=INTEGER}, #{payTypeName,jdbcType=VARCHAR}, ",
        "#{isEnabled,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PfCorderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfCorderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfCorderPayment> selectByExample(PfCorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, pf_corder_id, amount, pay_type_id, pay_type_name, is_enabled, ",
        "remark",
        "from pf_corder_payment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PfCorderPayment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfCorderPayment record, @Param("example") PfCorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfCorderPayment record, @Param("example") PfCorderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PfCorderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pf_corder_payment",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "pf_corder_id = #{pfCorderId,jdbcType=BIGINT},",
          "amount = #{amount,jdbcType=DECIMAL},",
          "pay_type_id = #{payTypeId,jdbcType=INTEGER},",
          "pay_type_name = #{payTypeName,jdbcType=VARCHAR},",
          "is_enabled = #{isEnabled,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PfCorderPayment record);
}