package com.masiis.shop.dao;

import com.masiis.shop.dao.PfCorderOperationLog;
import com.masiis.shop.dao.PfCorderOperationLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PfCorderOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfCorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfCorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pf_corder_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_corder_operation_log (id, create_time, ",
        "create_man, pf_corder_id, ",
        "pf_corder_status, remark)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createMan,jdbcType=BIGINT}, #{pfCorderId,jdbcType=BIGINT}, ",
        "#{pfCorderStatus,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PfCorderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfCorderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfCorderOperationLog> selectByExample(PfCorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, create_man, pf_corder_id, pf_corder_status, remark",
        "from pf_corder_operation_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    PfCorderOperationLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfCorderOperationLog record, @Param("example") PfCorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfCorderOperationLog record, @Param("example") PfCorderOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PfCorderOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_corder_operation_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pf_corder_operation_log",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_man = #{createMan,jdbcType=BIGINT},",
          "pf_corder_id = #{pfCorderId,jdbcType=BIGINT},",
          "pf_corder_status = #{pfCorderStatus,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PfCorderOperationLog record);
}