package com.masiis.shop.dao;

import com.masiis.shop.dao.PfSkuAgent;
import com.masiis.shop.dao.PfSkuAgentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PfSkuAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(PfSkuAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(PfSkuAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from pf_sku_agent",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into pf_sku_agent (id, sku_id, ",
        "agent_level_id, discount, ",
        "quantity, remark)",
        "values (#{id,jdbcType=INTEGER}, #{skuId,jdbcType=INTEGER}, ",
        "#{agentLevelId,jdbcType=INTEGER}, #{discount,jdbcType=DECIMAL}, ",
        "#{quantity,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PfSkuAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(PfSkuAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<PfSkuAgent> selectByExample(PfSkuAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, sku_id, agent_level_id, discount, quantity, remark",
        "from pf_sku_agent",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PfSkuAgent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfSkuAgent record, @Param("example") PfSkuAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") PfSkuAgent record, @Param("example") PfSkuAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(PfSkuAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_sku_agent
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update pf_sku_agent",
        "set sku_id = #{skuId,jdbcType=INTEGER},",
          "agent_level_id = #{agentLevelId,jdbcType=INTEGER},",
          "discount = #{discount,jdbcType=DECIMAL},",
          "quantity = #{quantity,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PfSkuAgent record);
}