package com.masiis.shop.dao;

import java.util.Date;

public class PfUserSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.agent_level_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer agentLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.is_pay
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.is_certificate
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.pf_corder_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long pfCorderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.is_authorized
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer isAuthorized;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_sku.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.id
     *
     * @return the value of pf_user_sku.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.id
     *
     * @param id the value for pf_user_sku.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.create_time
     *
     * @return the value of pf_user_sku.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.create_time
     *
     * @param createTime the value for pf_user_sku.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.code
     *
     * @return the value of pf_user_sku.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.code
     *
     * @param code the value for pf_user_sku.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.pid
     *
     * @return the value of pf_user_sku.pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.pid
     *
     * @param pid the value for pf_user_sku.pid
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.sku_id
     *
     * @return the value of pf_user_sku.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.sku_id
     *
     * @param skuId the value for pf_user_sku.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.agent_level_id
     *
     * @return the value of pf_user_sku.agent_level_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getAgentLevelId() {
        return agentLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.agent_level_id
     *
     * @param agentLevelId the value for pf_user_sku.agent_level_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAgentLevelId(Integer agentLevelId) {
        this.agentLevelId = agentLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.is_pay
     *
     * @return the value of pf_user_sku.is_pay
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsPay() {
        return isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.is_pay
     *
     * @param isPay the value for pf_user_sku.is_pay
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsPay(Integer isPay) {
        this.isPay = isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.is_certificate
     *
     * @return the value of pf_user_sku.is_certificate
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsCertificate() {
        return isCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.is_certificate
     *
     * @param isCertificate the value for pf_user_sku.is_certificate
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsCertificate(Integer isCertificate) {
        this.isCertificate = isCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.pf_corder_id
     *
     * @return the value of pf_user_sku.pf_corder_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getPfCorderId() {
        return pfCorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.pf_corder_id
     *
     * @param pfCorderId the value for pf_user_sku.pf_corder_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPfCorderId(Long pfCorderId) {
        this.pfCorderId = pfCorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.is_authorized
     *
     * @return the value of pf_user_sku.is_authorized
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getIsAuthorized() {
        return isAuthorized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.is_authorized
     *
     * @param isAuthorized the value for pf_user_sku.is_authorized
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIsAuthorized(Integer isAuthorized) {
        this.isAuthorized = isAuthorized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_sku.remark
     *
     * @return the value of pf_user_sku.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_sku.remark
     *
     * @param remark the value for pf_user_sku.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}