package com.masiis.shop.dao;

import java.util.Date;

public class PfUserCertificate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.pf_user_sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer pfUserSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.spu_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer spuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.id_card
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.wx_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String wxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.begin_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.end_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.agent_level_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer agentLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_user_certificate.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.id
     *
     * @return the value of pf_user_certificate.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.id
     *
     * @param id the value for pf_user_certificate.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.create_time
     *
     * @return the value of pf_user_certificate.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.create_time
     *
     * @param createTime the value for pf_user_certificate.create_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.code
     *
     * @return the value of pf_user_certificate.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.code
     *
     * @param code the value for pf_user_certificate.code
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.pf_user_sku_id
     *
     * @return the value of pf_user_certificate.pf_user_sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getPfUserSkuId() {
        return pfUserSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.pf_user_sku_id
     *
     * @param pfUserSkuId the value for pf_user_certificate.pf_user_sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setPfUserSkuId(Integer pfUserSkuId) {
        this.pfUserSkuId = pfUserSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.user_id
     *
     * @return the value of pf_user_certificate.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.user_id
     *
     * @param userId the value for pf_user_certificate.user_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.spu_id
     *
     * @return the value of pf_user_certificate.spu_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.spu_id
     *
     * @param spuId the value for pf_user_certificate.spu_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.sku_id
     *
     * @return the value of pf_user_certificate.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.sku_id
     *
     * @param skuId the value for pf_user_certificate.sku_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.id_card
     *
     * @return the value of pf_user_certificate.id_card
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.id_card
     *
     * @param idCard the value for pf_user_certificate.id_card
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.mobile
     *
     * @return the value of pf_user_certificate.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.mobile
     *
     * @param mobile the value for pf_user_certificate.mobile
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.wx_id
     *
     * @return the value of pf_user_certificate.wx_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.wx_id
     *
     * @param wxId the value for pf_user_certificate.wx_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.begin_time
     *
     * @return the value of pf_user_certificate.begin_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.begin_time
     *
     * @param beginTime the value for pf_user_certificate.begin_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.end_time
     *
     * @return the value of pf_user_certificate.end_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.end_time
     *
     * @param endTime the value for pf_user_certificate.end_time
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.agent_level_id
     *
     * @return the value of pf_user_certificate.agent_level_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getAgentLevelId() {
        return agentLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.agent_level_id
     *
     * @param agentLevelId the value for pf_user_certificate.agent_level_id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setAgentLevelId(Integer agentLevelId) {
        this.agentLevelId = agentLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.img_url
     *
     * @return the value of pf_user_certificate.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.img_url
     *
     * @param imgUrl the value for pf_user_certificate.img_url
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.status
     *
     * @return the value of pf_user_certificate.status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.status
     *
     * @param status the value for pf_user_certificate.status
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_user_certificate.remark
     *
     * @return the value of pf_user_certificate.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_user_certificate.remark
     *
     * @param remark the value for pf_user_certificate.remark
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}