package com.masiis.shop.dao;

import com.masiis.shop.dao.SfOrderPayment;
import com.masiis.shop.dao.SfOrderPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SfOrderPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_order_payment (id)",
        "values (#{id,jdbcType=BIGINT})"
    })
    int insert(SfOrderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfOrderPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfOrderPayment> selectByExample(SfOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfOrderPayment record, @Param("example") SfOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_payment
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfOrderPayment record, @Param("example") SfOrderPaymentExample example);
}