package com.masiis.shop.dao;

import com.masiis.shop.dao.SfOrderConsignee;
import com.masiis.shop.dao.SfOrderConsigneeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SfOrderConsigneeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfOrderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfOrderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from sf_order_consignee",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_order_consignee (id)",
        "values (#{id,jdbcType=BIGINT})"
    })
    int insert(SfOrderConsignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfOrderConsignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfOrderConsignee> selectByExample(SfOrderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfOrderConsignee record, @Param("example") SfOrderConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_order_consignee
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfOrderConsignee record, @Param("example") SfOrderConsigneeExample example);
}