package com.masiis.shop.dao;

import com.masiis.shop.dao.SfShopStatistics;
import com.masiis.shop.dao.SfShopStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SfShopStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_statistics
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfShopStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_statistics
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfShopStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_statistics
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_shop_statistics (id)",
        "values (#{id,jdbcType=BIGINT})"
    })
    int insert(SfShopStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_statistics
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfShopStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_statistics
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfShopStatistics> selectByExample(SfShopStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_statistics
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfShopStatistics record, @Param("example") SfShopStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_statistics
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfShopStatistics record, @Param("example") SfShopStatisticsExample example);
}