package com.masiis.shop.dao;

import com.masiis.shop.dao.SfShopCart;
import com.masiis.shop.dao.SfShopCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SfShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_cart
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_cart
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_cart
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_shop_cart (id)",
        "values (#{id,jdbcType=BIGINT})"
    })
    int insert(SfShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_cart
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_cart
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfShopCart> selectByExample(SfShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_cart
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfShopCart record, @Param("example") SfShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_shop_cart
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfShopCart record, @Param("example") SfShopCartExample example);
}