package com.masiis.shop.dao;

public class SfShopStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_shop_statistics.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_shop_statistics.id
     *
     * @return the value of sf_shop_statistics.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_shop_statistics.id
     *
     * @param id the value for sf_shop_statistics.id
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }
}