package com.masiis.shop.dao;

import com.masiis.shop.dao.SfSkuDistribution;
import com.masiis.shop.dao.SfSkuDistributionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SfSkuDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfSkuDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfSkuDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from sf_sku_distribution",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_sku_distribution (id, sku_id, ",
        "sort, discount, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{skuId,jdbcType=INTEGER}, ",
        "#{sort,jdbcType=INTEGER}, #{discount,jdbcType=DECIMAL}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(SfSkuDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfSkuDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfSkuDistribution> selectByExample(SfSkuDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, sku_id, sort, discount, remark",
        "from sf_sku_distribution",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SfSkuDistribution selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfSkuDistribution record, @Param("example") SfSkuDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfSkuDistribution record, @Param("example") SfSkuDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(SfSkuDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_sku_distribution
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update sf_sku_distribution",
        "set sku_id = #{skuId,jdbcType=INTEGER},",
          "sort = #{sort,jdbcType=INTEGER},",
          "discount = #{discount,jdbcType=DECIMAL},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SfSkuDistribution record);
}