package com.masiis.shop.dao;

import com.masiis.shop.dao.SfUserBrokerageLog;
import com.masiis.shop.dao.SfUserBrokerageLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SfUserBrokerageLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfUserBrokerageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfUserBrokerageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_user_brokerage_log (id)",
        "values (#{id,jdbcType=BIGINT})"
    })
    int insert(SfUserBrokerageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfUserBrokerageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfUserBrokerageLog> selectByExample(SfUserBrokerageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfUserBrokerageLog record, @Param("example") SfUserBrokerageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage_log
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfUserBrokerageLog record, @Param("example") SfUserBrokerageLogExample example);
}