package com.masiis.shop.dao;

import com.masiis.shop.dao.SfUserBrokerage;
import com.masiis.shop.dao.SfUserBrokerageExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SfUserBrokerageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfUserBrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfUserBrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_user_brokerage (id)",
        "values (#{id,jdbcType=BIGINT})"
    })
    int insert(SfUserBrokerage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfUserBrokerage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfUserBrokerage> selectByExample(SfUserBrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfUserBrokerage record, @Param("example") SfUserBrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_brokerage
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfUserBrokerage record, @Param("example") SfUserBrokerageExample example);
}