package com.masiis.shop.dao;

import com.masiis.shop.dao.SfUserRelation;
import com.masiis.shop.dao.SfUserRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SfUserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int countByExample(SfUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int deleteByExample(SfUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Delete({
        "delete from sf_user_relation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Insert({
        "insert into sf_user_relation (id, create_time, ",
        "user_id, parent_user_id, ",
        "remark)",
        "values (#{id,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{userId,jdbcType=BIGINT}, #{parentUserId,jdbcType=BIGINT}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(SfUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int insertSelective(SfUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    List<SfUserRelation> selectByExample(SfUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Select({
        "select",
        "id, create_time, user_id, parent_user_id, remark",
        "from sf_user_relation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SfUserRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SfUserRelation record, @Param("example") SfUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByExample(@Param("record") SfUserRelation record, @Param("example") SfUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    int updateByPrimaryKeySelective(SfUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_user_relation
     *
     * @mbggenerated Wed Mar 02 12:09:53 CST 2016
     */
    @Update({
        "update sf_user_relation",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "parent_user_id = #{parentUserId,jdbcType=BIGINT},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SfUserRelation record);
}