package com.masiis.shop.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class ComSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.id
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.name
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.spu_id
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private Integer spuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.create_time
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.create_man
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private Long createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.modify_time
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.modify_man
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private Long modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.bar_code
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.price_cost
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private BigDecimal priceCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.price_market
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private BigDecimal priceMarket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.price_retail
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private BigDecimal priceRetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_sku.remark
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.id
     *
     * @return the value of com_sku.id
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.id
     *
     * @param id the value for com_sku.id
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.name
     *
     * @return the value of com_sku.name
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.name
     *
     * @param name the value for com_sku.name
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.spu_id
     *
     * @return the value of com_sku.spu_id
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.spu_id
     *
     * @param spuId the value for com_sku.spu_id
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.create_time
     *
     * @return the value of com_sku.create_time
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.create_time
     *
     * @param createTime the value for com_sku.create_time
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.create_man
     *
     * @return the value of com_sku.create_man
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public Long getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.create_man
     *
     * @param createMan the value for com_sku.create_man
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setCreateMan(Long createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.modify_time
     *
     * @return the value of com_sku.modify_time
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.modify_time
     *
     * @param modifyTime the value for com_sku.modify_time
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.modify_man
     *
     * @return the value of com_sku.modify_man
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public Long getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.modify_man
     *
     * @param modifyMan the value for com_sku.modify_man
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setModifyMan(Long modifyMan) {
        this.modifyMan = modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.bar_code
     *
     * @return the value of com_sku.bar_code
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.bar_code
     *
     * @param barCode the value for com_sku.bar_code
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.price_cost
     *
     * @return the value of com_sku.price_cost
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public BigDecimal getPriceCost() {
        return priceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.price_cost
     *
     * @param priceCost the value for com_sku.price_cost
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setPriceCost(BigDecimal priceCost) {
        this.priceCost = priceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.price_market
     *
     * @return the value of com_sku.price_market
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public BigDecimal getPriceMarket() {
        return priceMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.price_market
     *
     * @param priceMarket the value for com_sku.price_market
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setPriceMarket(BigDecimal priceMarket) {
        this.priceMarket = priceMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.price_retail
     *
     * @return the value of com_sku.price_retail
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public BigDecimal getPriceRetail() {
        return priceRetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.price_retail
     *
     * @param priceRetail the value for com_sku.price_retail
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setPriceRetail(BigDecimal priceRetail) {
        this.priceRetail = priceRetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_sku.remark
     *
     * @return the value of com_sku.remark
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_sku.remark
     *
     * @param remark the value for com_sku.remark
     *
     * @mbggenerated Wed Mar 09 11:18:30 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}