package com.masiis.shop.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class ComSpu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.name
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.brand_id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.create_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.create_man
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Long createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.up_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.down_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Date downTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.modify_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.modify_man
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Long modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.category_id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.category_name
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.status
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.slogan
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private String slogan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.is_sale
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Integer isSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.is_delete
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.is_trial
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Integer isTrial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.weight
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Long weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.pack_length
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Long packLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.pack_width
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Long packWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.pack_height
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private Long packHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.ship_amount
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private BigDecimal shipAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.remark
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.art_no
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private String artNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_spu.content
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.id
     *
     * @return the value of com_spu.id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.id
     *
     * @param id the value for com_spu.id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.name
     *
     * @return the value of com_spu.name
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.name
     *
     * @param name the value for com_spu.name
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.brand_id
     *
     * @return the value of com_spu.brand_id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.brand_id
     *
     * @param brandId the value for com_spu.brand_id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.create_time
     *
     * @return the value of com_spu.create_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.create_time
     *
     * @param createTime the value for com_spu.create_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.create_man
     *
     * @return the value of com_spu.create_man
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Long getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.create_man
     *
     * @param createMan the value for com_spu.create_man
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setCreateMan(Long createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.up_time
     *
     * @return the value of com_spu.up_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.up_time
     *
     * @param upTime the value for com_spu.up_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.down_time
     *
     * @return the value of com_spu.down_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Date getDownTime() {
        return downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.down_time
     *
     * @param downTime the value for com_spu.down_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setDownTime(Date downTime) {
        this.downTime = downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.modify_time
     *
     * @return the value of com_spu.modify_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.modify_time
     *
     * @param modifyTime the value for com_spu.modify_time
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.modify_man
     *
     * @return the value of com_spu.modify_man
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Long getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.modify_man
     *
     * @param modifyMan the value for com_spu.modify_man
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setModifyMan(Long modifyMan) {
        this.modifyMan = modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.category_id
     *
     * @return the value of com_spu.category_id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.category_id
     *
     * @param categoryId the value for com_spu.category_id
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.category_name
     *
     * @return the value of com_spu.category_name
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.category_name
     *
     * @param categoryName the value for com_spu.category_name
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.status
     *
     * @return the value of com_spu.status
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.status
     *
     * @param status the value for com_spu.status
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.slogan
     *
     * @return the value of com_spu.slogan
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.slogan
     *
     * @param slogan the value for com_spu.slogan
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan == null ? null : slogan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.is_sale
     *
     * @return the value of com_spu.is_sale
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Integer getIsSale() {
        return isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.is_sale
     *
     * @param isSale the value for com_spu.is_sale
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setIsSale(Integer isSale) {
        this.isSale = isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.is_delete
     *
     * @return the value of com_spu.is_delete
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.is_delete
     *
     * @param isDelete the value for com_spu.is_delete
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.is_trial
     *
     * @return the value of com_spu.is_trial
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Integer getIsTrial() {
        return isTrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.is_trial
     *
     * @param isTrial the value for com_spu.is_trial
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setIsTrial(Integer isTrial) {
        this.isTrial = isTrial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.weight
     *
     * @return the value of com_spu.weight
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.weight
     *
     * @param weight the value for com_spu.weight
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.pack_length
     *
     * @return the value of com_spu.pack_length
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Long getPackLength() {
        return packLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.pack_length
     *
     * @param packLength the value for com_spu.pack_length
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setPackLength(Long packLength) {
        this.packLength = packLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.pack_width
     *
     * @return the value of com_spu.pack_width
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Long getPackWidth() {
        return packWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.pack_width
     *
     * @param packWidth the value for com_spu.pack_width
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setPackWidth(Long packWidth) {
        this.packWidth = packWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.pack_height
     *
     * @return the value of com_spu.pack_height
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public Long getPackHeight() {
        return packHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.pack_height
     *
     * @param packHeight the value for com_spu.pack_height
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setPackHeight(Long packHeight) {
        this.packHeight = packHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.ship_amount
     *
     * @return the value of com_spu.ship_amount
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public BigDecimal getShipAmount() {
        return shipAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.ship_amount
     *
     * @param shipAmount the value for com_spu.ship_amount
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setShipAmount(BigDecimal shipAmount) {
        this.shipAmount = shipAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.remark
     *
     * @return the value of com_spu.remark
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.remark
     *
     * @param remark the value for com_spu.remark
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.art_no
     *
     * @return the value of com_spu.art_no
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public String getArtNo() {
        return artNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.art_no
     *
     * @param artNo the value for com_spu.art_no
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setArtNo(String artNo) {
        this.artNo = artNo == null ? null : artNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_spu.content
     *
     * @return the value of com_spu.content
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_spu.content
     *
     * @param content the value for com_spu.content
     *
     * @mbggenerated Wed Mar 09 10:23:03 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}