<%@ page language="java" import="java.util.*" contentType="text/html; utf-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"> 
    <title>麦链合伙人</title>
    <link rel="stylesheet" href="<%=path%>/static/css/base.css">
    <link rel="stylesheet" href="<%=path%>/static/css/reset.css">
    <link rel="stylesheet" href="<%=path%>/static/css/header.css">
    <style>
        /* Generated by less 2.5.1 */
            .wrap main {
              margin-top: 10px;
            }
        .wrap main .floor {
            background: #fff;
            margin-top: 10px;
            padding: 5px 0;
        }
        .wrap main .floor div {
            display: -webkit-box;
            padding: 5px 10px;
            position: relative;
            -webkit-box-align: center;
        }
        .wrap main .floor div span {
            display: block;
            width: 14%;
        }
        .wrap main .floor div label {
            display: block;
            border: 1px solid #CBCBCB;
            z-index: 10;
            background: #ffffff url("/static/images/selectdown.png") no-repeat 95%;
            background-size: 14px;
            height: 25px;
            position: relative;
        }
        .wrap main .floor div label b {
            display: block;
            padding-left: 10px;
            color: #666;
            line-height: 27px;
            width: 80%;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }
        .wrap main .floor div .goods {
            width: 50%;
            margin-right: 10px;
        }
        .wrap main .floor div label select {
            position: absolute;
            left:0;
            top:0;
            height:27px;
            opacity: 0;
        }
    .wrap main .sec1 {
              height: 60px;
              display: -webkit-box;
              padding: 10px;
              border-bottom: 1px solid #f6f6f6;
              background: #ffffff url("<%=path%>/static/images/tuijian_6.jpg") no-repeat no-repeat 96%;
              background-size: 10px;
            }
            .wrap main .sec1 img {
              width: 60px;
              height: 60px;
              border-radius: 50px;
            }
            .wrap main .sec1 div {
              -webkit-box-flex: 1;
              margin-left: 10px;
              display: -webkit-box;
              -webkit-box-orient: vertical;
            }
            .wrap main .sec1 div p {
              margin: 5px;
            }
            .wrap main .sec1 div p b {
              font-size: 12px;
              color: #f74a11;
                margin-left: 30px;
            }
    </style>
</head>
<body>
   <div class="wrap">
        <header class="xq_header">
                  <a href="javascript:window.history.go(-1);"><img src="<%=path%>/static/images/xq_rt.png" alt=""></a>
                    <p>帮我推荐</p>            
        </header>
        <main>
            <div class="floor">
                <div>
                    <span>商品：</span>
                    <label for="goods" class="goods">
                        <b></b>
                        <select id="goods" class="myValue">
                            <option value="">全部</option>
                            <c:forEach items="${agentSkus}" var="sku">
                                <option value="${sku.id}" <c:if test="${sku.id == skuId}">selected</c:if> >${sku.name}</option>
                            </c:forEach>
                        </select>
                    </label>
                </div>
            </div>

            <div class="floor2">
            <c:forEach items="${sumByUser}" var="sum">
             <div class="sec1" onclick="javascript:window.location.href = '<%=basePath%>myRecommend/giveRecommend?userId=${sum.userId}&skuId=${sum.skuId}';">
                <img src="${sum.wxHeadImg}" alt="">
                <div>
                    <p>${sum.name}<b>推荐人数 ${sum.number}人</b></p>
                    <p>${sum.skuName}</p>
                </div>
            </div>
            </c:forEach>
            </div>
        </main>
    </div>
   <script src="<%=path%>/static/js/jquery-1.8.3.min.js"></script>
   <script>
       $(document).ready(function(){
           var goodsWidth=$(".goods").width();
           $(".goods b").html($("#goods option:selected").text());
           $("#goods").width(goodsWidth);
       })
       $("#goods").on("change",function(){
           var skuId=$("#goods option:selected").val();
           window.location.href = skuId ? '<%=basePath%>myRecommend/recommendGiveList?skuId='+skuId : '<%=basePath%>myRecommend/recommendGiveList';
       })

       $(".myValue").on("change",function(){
           var skuId = $("#goods").val()
           $(".floor2").html("");
           $.ajax({
               type:"POST",
               url : "<%=path%>/myRecommend/giveRecommendLike.do",
               data:{skuId:skuId},
               dataType:"Json",
               success:function(data){
                   var trHtml = "";
                   $.each(data, function(i, userRecommend) {
                       trHtml+="<div class=\"sec1\" ";
                       trHtml+="onclick=\"javascript:window.location.replace('<%=basePath%>myRecommend/giveRecommend?userId="+userRecommend.userId+"&skuId="+userRecommend.skuId+"')\" >";
                       trHtml+="<img src=\""+userRecommend.wxHeadImg+"\" alt=\"\">";
                       trHtml+="<div> <p>"+userRecommend.name+" <b>推荐人数 "+userRecommend.number+"</b></p>";
                       trHtml+="<p>"+userRecommend.skuName+"</p> </div> </div>";
                   })
                   $(".floor2").html(trHtml);
               }
           })
       })
   </script>
</body>
</html>