<%@ page language="java" import="java.util.*" contentType="text/html; utf-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"> 
    <title>麦链合伙人</title>
    <link rel="stylesheet" href="<%=path%>/static/css/base.css">
    <link rel="stylesheet" href="<%=path%>/static/css/reset.css">
    <link rel="stylesheet" href="<%=path%>/static/css/header.css">
    <style>
        /* Generated by less 2.5.1 */
            .wrap main {
              margin-top: 10px;
            }
            .wrap main .sec1 {
              height: 60px;
              display: -webkit-box;
              padding: 10px;
              border-bottom: 1px solid #f6f6f6;
              background: #ffffff url("<%=path%>/static/images/tuijian_6.jpg") no-repeat no-repeat 96%;
              background-size: 10px;
            }
            .wrap main .sec1 img {
              width: 60px;
              height: 60px;
              border-radius: 50px;
            }
            .wrap main .sec1 div {
              -webkit-box-flex: 1;
              margin-left: 10px;
              display: -webkit-box;
              -webkit-box-orient: vertical;
            }
            .wrap main .sec1 div p {
              margin: 5px;
            }
            .wrap main .sec1 div p b {
              font-size: 12px;
              color: #f74a11;
                margin-left: 30px;
            }

    </style>
</head>
<body>
   <div class="wrap">
        <header class="xq_header">
                  <a href="<%=path%>/myRecommend/feeList"><img src="<%=path%>/static/images/xq_rt.png" alt=""></a>
                    <p>帮我推荐</p>            
        </header>
        <main>
            <c:forEach items="${sumByUser}" var="sum">
             <div class="sec1" onclick="javascript:window.location.replace('<%=basePath%>myRecommend/giveRecommend?userId=${sum.userId}&skuId=${sum.skuId}')">
                <img src="${sum.wxHeadImg}" alt="">
                <div>
                    <p>${sum.name}<b>推荐人数 ${sum.number}人</b></p>
                    <p>${sum.skuName}</p>
                </div>
            </div>
            </c:forEach>
        </main>
    </div>
    <script src="<%=path%>/static/js/jquery-1.8.3.min.js"></script>
</body>
</html>